baseURL = "https://ad4noobs.justin-p.me"
languageCode = "en-us"
title = "AD4Noobs"

theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/AD4Noobs/site/edit/main/content/"
  author = "Justin Perdok"
  description = "A 'guide' to teach Active Directory to Noobs"
  showVisitedLinks = true
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLandingPageButton = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableMermaid = true
  #customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = ""

[outputs]
  home = [ "HTML", "RSS", "JSON"]
